# -*- coding: utf-8 -*-
"""extract_curve

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AKzHJtY1Ngfutwm_aZ4Urzgc0A1Jkd2h
"""

from cryptography import x509
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives.asymmetric import ec

# Change the filename to your actual certificate name
with open("bits.crt", "rb") as file:
    cert = x509.load_pem_x509_certificate(file.read(), default_backend())

public_key = cert.public_key()

if isinstance(public_key, ec.EllipticCurvePublicKey):
    curve = public_key.curve.name.lower()

    print("Elliptic Curve Name:", curve)
    print("Key Size:", public_key.curve.key_size, "bits")

    curve_db = {
        "secp256r1": ("y² = x³ - 3x + b (mod p)", "p = 2^256 − 2^224 + 2^192 + 2^96 − 1"),
        "secp384r1": ("y² = x³ - 3x + b (mod p)", "p = 2^384 − 2^128 − 2^96 + 2^32 − 1"),
        "secp521r1": ("y² = x³ - 3x + b (mod p)", "p = 2^521 − 1")
    }

    if curve in curve_db:
        print("Curve Equation:", curve_db[curve][0])
        print("Field Characteristic:", curve_db[curve][1])
    else:
        print("Curve not in database")

else:
    print("This is not an ECC certificate.")